# Generated by Django 5.2.4 on 2025-07-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marmitas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marmita',
            name='criada_por',
        ),
    ]
