# Generated by Django 5.2.4 on 2025-07-29 01:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marmitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('numero_endereco', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=100)),
                ('numero_telefone', models.CharField(max_length=20)),
                ('esta_ativo', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('cozinheiro', 'Cozinheiro'), ('admin', 'Admin'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendamentoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', models.CharField(choices=[('Segunda Feira', 'segunda feira'), ('Terça Feira', 'terça feira'), ('Quarta Feira', 'quarta feira'), ('Quinta Feira', 'quinta feira'), ('Sexta Feira', 'sexta feira'), ('Sabado', 'sabado'), ('Domingo', 'domingo')], max_length=30)),
                ('hora', models.TimeField(default='12:00')),
                ('ativo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('marmita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marmitas.marmita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'pendente'), ('Em_Andamento', 'em_andamento'), ('Em_Entrega', 'em_entrega'), ('Finalizado', 'finalizado'), ('Cancelado', 'cancelado')], default='Pendente', max_length=20)),
                ('marmita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marmitas.marmita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(null=True)),
                ('codigo', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('marmita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marmitas.marmita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resturante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
